### ISSUE TITLE
Local storage quotum reached in Firefox

### ISSUE THREAD

**Issue by wouterbeek** [Triply-Dev/YASGUI.YASR-deprecated#100]
Copy/paste from the Firefox developer tools:

```
DOMException [NS_ERROR_DOM_QUOTA_REACHED: "Persistent storage maximum size reached"
code: 1014
nsresult: 0x805303f6
location: http://static.triply.cc/assets/js/yasgui.min.js?v=1:28]  yasgui.min.js:41:7236
TypeError: t.yasgui is undefined[Learn More]
```

**Comment by LaurensRietveld** [comment]
This is now handled more gracefully since https://github.com/OpenTriply/YASGUI.YASR/commit/bfc6f2f7fc09dba59eeae80567d1d57dcb722626

We won't get a DOM exception anymore. Instead, a warning is logged, and nothing is stored to localstorage. Implementors that use YASR may choose to set the `onQuotaExceeded` value in order to cleanup the localstorage
