### ISSUE TITLE
Pivot table drag&drop does not work on iOS

### ISSUE THREAD

**Issue by d0rg0ld** [Triply-Dev/YASGUI.YASR-deprecated#117]
Hi there,

I just heard the YASGUI presentation at ISWC2017, this is great work!

Playing around with the tool on my Ipad led me to an issue in the pivot creation tab in IOS I’d like to report:

It appears that it is not possible to drag the available variables to the row/column areas for pivoting, which is a pity because otherwise it seems to work well on the mobile platform

Thanks and best regards,
Doron

**Comment by LaurensRietveld** [comment]
As we're using quite some UI third-party libraries when rendering results, it'll be difficult making a smooth mobile browser experience.
A benefit though: posting this issue at the original libraries means a possible fix will propagate to yasgui. I.e., if this is still an issue, I'd suggest posting this bug here: https://github.com/nicolaskruchten/pivottable
