### ISSUE TITLE
Suggestion: Consider fetchTitlesFromPreflabel for CONSTRUCT/DESCRIBE output

### ISSUE THREAD

**Issue by jneubert** [Triply-Dev/YASGUI.YASR-deprecated#16]
Particularly in these results the display of a label at uri hover would be helpful.

**Comment by LaurensRietveld** [comment]
I'd like this. Here, we shouldnt have a problem with changing the content as well (which, in a table layout would influence the column/row positions heavily)

But: we'd need some proper parsers to do this. We'd need to fetch e.g. defined prefixes, to know what we are searching for. 

So, this is dependent on issue #19 and #20

**Comment by jneubert** [comment]
Ah, I wasn't clear with my suggestion: I absolutely like the turtle output, because it groups things nicely, so tables probably would look worse. My - perhaps naive - idea was that, as you can recognize a URI syntactically for highlighting, it could be possible to attach the functionality to it.

**Comment by LaurensRietveld** [comment]
I understand: grabbing solely a complete URI in a blob of text and replacing it (on hover) with a label should be straight forward.
The problem is mostly completeness (and perhaps avoiding false positives)
For this to be as complete as possible we'd need to know the defined prefixes in the resultset.
We could do this with a regex, but for robustness using a proper parser would be preferable.

And, the added advantage of using parsers is that we can visualize these construct results as a regular table as well

**Comment by jneubert** [comment]
Oh, I see - I didn't consider the prefixes. 

Having both options for display would be nice, too. Hopefully, a fine table component turns out.

**Comment by LaurensRietveld** [comment]
Just cleaning up old issues. 
I'll close this one, because:
- another dependency on preflabel (which still works, but is unsupported atm) is not preferable 
- this requires a parsing lib (for a variety of rdf serializations) that would make the dependency list even bigger than it is now
