### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by scampi** [Triply-Dev/YASGUI.YASR-deprecated#37]
If I send a bad request to Virtuoso, the exaplanation is not showed. Instead, I just get the message `error: Bad Request`. It would be good to show the message returned by virtuoso.

**Comment by LaurensRietveld** [comment]
Do you have an example of a query going wrong? And do you have a link to your deployed version of YASR?
If I send an incorrect query via the yasr.yasgui.org demo, it seems to work fine

**Comment by scampi** [comment]
Thanks Laurens for looking into it.

The query is:

``` sql
select (uri(?o) as ?urio) WHERE {
  ?s ?p ?o
  filter isliteral(?o)
}
limit 10
```

The problem is that the built-in `uri` is not in virtuoso, but `iri` is. You can try this at http://scampi.github.io/gosparqled/

**Comment by LaurensRietveld** [comment]
This is something that should be fixed in the newest version. I suggest you update to the latest YASQE and YASR libraries, and update the final few lines in your autocompletions.js file. You can remove the success and error handlers, and replace this with the following line: 

`yasqe.options.sparql.callbacks.complete = yasr.setResponse;`
