### ISSUE TITLE
datatables from npm

### ISSUE THREAD

**Issue by aindlq** [Triply-Dev/YASGUI.YASR-deprecated#73]
Are there any reasons why yasr doesn't use datatables from npm?

**Comment by LaurensRietveld** [comment]
To be honest, I don't remember. I tried to include all dependencies via npm, but that wasnt always possible because of a lacking package definition, or because the libraries did not expose themselves properly as amd/commonjs modules 
Not sure which reason was applicable for datatables. 

But I'll take a look at the next version and see whether we can include it as proper npm module

**Comment by aindlq** [comment]
I've already tried it. Will test it and if everything works will submit pull request.

**Comment by LaurensRietveld** [comment]
Excellent!
