### ISSUE TITLE
Column width should adapt to content size

### ISSUE THREAD

**Issue by jneubert** [Triply-Dev/YASGUI.YASR-deprecated#78]
Column width seems to be equal for each column, which is bad when the column contents is very different in size. See [this query](http://zbw.eu/beta/sparql-lab/?endpoint=http://zbw.eu/beta/sparql/stw/query&queryRef=https://api.github.com/repos/jneubert/sparql-queries/contents/stw/categories_by_descriptors.rq) for an example - the resulting display is:

![columns](https://cloud.githubusercontent.com/assets/2128921/8281057/6981903c-18e4-11e5-91be-7711bac7c43f.png)

YASR 2.6.0, Firefox and Chrome

**Comment by wouterbeek** [comment]
I see your point, but I also think that there a benefit to having stable default column widths (my 2 cents).

**Comment by jneubert** [comment]
Well - what do you see as the benefit of stable default column widths?

**Comment by jneubert** [comment]
In use cases where column contents differs much in length (as in the example above) I suppose an adaption would be helpful for everybody. I've just checked on https://www.datatables.net/ that the jquery plugin supports adaptable column widths (see the example table on the home page).

**Comment by wouterbeek** [comment]
@jneubert DataTables seems to calculate the maximum width for all the values that appear in each column beforehand.  I hadn't though of that earlier.  Specifically, I had understood your idea as determining the column width for each page in a result set independently.  Paging through the result set would then result in annoying resizes of the column widths.

However, since result sets that can be displayed inside a web browser are small anyway (say, <1,000 results), it is actually possible to dynamically assess column width per *result set* i.o. per *page*.  Now I am more in favor of your suggestion :-)

**Comment by jneubert** [comment]
Sorry, I have not made that explicit: The idea was not to recalculate column width for every page (which indeed could be annoying), but for the whole result set. So we completely agree in that.

**Comment by LaurensRietveld** [comment]
I've turned on the autowidth for columns. Lets wait and see whether there are unexpected side-effects (I vaguely remember having this setting turned on a long time ago, but explicitly turning it off again because of such side effects)
