### ISSUE TITLE
Provide some form of integration with RAW?

### ISSUE THREAD

**Issue by pchampin** [Triply-Dev/YASGUI.YASR-deprecated#88]
I just stumbled upon the opensource project [RAW](http://app.raw.densitydesign.org/), which I find a very interesting alternative to proprietary tools such as Google charts.

I think it would be a good candidate for integration in YASR.

**Comment by LaurensRietveld** [comment]
that's the first time I head of this project. It seems very cool, and an integration with YASR would be very nice (PR welcomed though ;)). Only thing I'm hesitant about, is that the project seems to have stalled (last commit ~2 years ago). It should probably need some work as well, because:

- The api doc is pretty high level. Problems such as: How to link the download/export btn of yasr to the export functionality of raw? 
- We'd need to write a RAW parser for SPARQL results. This shouldn't be a lot of work though
- It includes some images (thumbnails), that I'd like to avoid. They should be base-encoded and included in the YASR JS if possible, or replaced with SVGs. Not sure how easy this is with RAW
-

**Comment by wouterbeek** [comment]
The RAW project has become active again, i.e., many commits since November last year.

**Comment by LaurensRietveld** [comment]
Jep, I noticed, and it seems they removed the server-side dependency. it's definitely more interesting now

**Comment by ktk** [comment]
RAW makes sense for many RDF related issues, especially related to RDF data cubes. We might think about how we could plug RDF related stuff to that, we thought about doing RDF/SPARQL integration as data source as well @zazuko

**Comment by wouterbeek** [comment]
Maybe the time is right to finally ditch the crappy Google Charts and start using D3/RAW for charts?

I agree with @ktk that this is best implemented+tested in a project where statistics are heavily used.  At @OpenTriply we do not have such a project ATM, but we could collaborate with someone who has (just drop me an email over at wouter@triply.cc).

**Comment by LaurensRietveld** [comment]
Continuing here https://github.com/TriplyDB/Yasgui/issues/134
